import client from '@/api/client.js';
import type { FlowNodeFull } from '@/types';

export class NodeDao {
  async getAll(): Promise<FlowNodeFull[]> {
    const { data } = await client.get('/nodes');
    return data;
  }

  async getByPhase(phaseId: number): Promise<FlowNodeFull[]> {
    const { data } = await client.get('/nodes', { params: { phaseId } });
    return data;
  }

  async getById(id: string): Promise<FlowNodeFull | null> {
    try {
      const { data } = await client.get(`/nodes/${id}`);
      return data;
    } catch {
      return null;
    }
  }

  async create(id: string, title: string, type: string, detail: string, phaseId: number, deptId: number): Promise<void> {
    await client.post('/nodes', { title, type, detail, phaseId, deptId });
  }

  async update(nodeId: string, fields: { title?: string; type?: string; detail?: string; phaseId?: number; deptId?: number }): Promise<void> {
    await client.put(`/nodes/${nodeId}`, fields);
  }

  async delete(nodeId: string): Promise<void> {
    await client.delete(`/nodes/${nodeId}`);
  }

  async updatePhase(nodeId: string, newPhaseId: number): Promise<void> {
    await client.patch(`/nodes/${nodeId}/phase`, { phaseId: newPhaseId });
  }

  async updateDept(nodeId: string, newDeptId: number): Promise<void> {
    await client.patch(`/nodes/${nodeId}/dept`, { deptId: newDeptId });
  }

  async updateDetail(nodeId: string, detail: string): Promise<void> {
    await client.patch(`/nodes/${nodeId}/detail`, { detail });
  }

  async updateSortOrder(phaseId: number, deptId: number, orders: { id: string; order: number }[]): Promise<void> {
    await client.post('/nodes/sort-order', { phaseId, deptId, orders });
  }

  async getMaxSortOrder(phaseId: number, deptId: number): Promise<number> {
    // Not directly exposed by API; frontend can infer from loaded nodes
    return 0;
  }

  async generateId(phaseId: number, deptId: number): Promise<string> {
    // ID is generated by backend; this method is kept for interface compatibility
    return '';
  }
}
